INCLUDEDIR=../include
include $(SHOME)/library/S_MAKE_FLAGS
include LOCAL_FILES

catch:
	@ echo "####  Do not run make in this directory."
locfit-s: $(OBJ)
	
.c.o:
	$(CC) $(CFLAGS) -DSVERSION -DGR -I$(INCLUDEDIR) -c $<
