INCLUDEDIR=../include
include ./LOCAL_FILES

catch:
	@ echo "####  Do not run make in this directory."
nda: $(OBJ);
	
.c.o:
	$(CC) $(CFLAGS) -DINTERFACE -DGR -I$(INCLUDEDIR) -c $<
clean:
	@ rm -f *.o
